spring.application.name=votingsystem

spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

server.port=${PORT:8080}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

app.admin.username=${APP_ADMIN_USERNAME}
app.admin.password=${APP_ADMIN_PASSWORD}